export const emp = [
  {
    ID: "1002",
    Name: "Bob Smith",
    Email: "bob.smith@example.com",
    Gender: "Male",
    Mobile: "9876543211",
    Designation: "Manager",
    Course: "B.Sc",
    Image: "bob.jpg",
  },
  {
    ID: "1003",
    Name: "Carol Williams",
    Email: "carol.williams@example.com",
    Gender: "Female",
    Mobile: "9876543212",
    Designation: "Developer",
    Course: "M.Tech",
    Image: "carol.jpg",
  },
  {
    ID: "1004",
    Name: "David Brown",
    Email: "david.brown@example.com",
    Gender: "Male",
    Mobile: "9876543213",
    Designation: "Analyst",
    Course: "MBA",
    Image: "david.jpg",
  },
  {
    ID: "1005",
    Name: "Emma Davis",
    Email: "emma.davis@example.com",
    Gender: "Female",
    Mobile: "9876543214",
    Designation: "Team Lead",
    Course: "BCA",
    Image: "emma.jpg",
  },
  {
    ID: "1006",
    Name: "Frank Miller",
    Email: "frank.miller@example.com",
    Gender: "Male",
    Mobile: "9876543215",
    Designation: "HR",
    Course: "MCA",
    Image: "frank.jpg",
  },
  {
    ID: "1007",
    Name: "Grace Lee",
    Email: "grace.lee@example.com",
    Gender: "Female",
    Mobile: "9876543216",
    Designation: "Manager",
    Course: "B.Sc",
    Image: "grace.jpg",
  },
  {
    ID: "1008",
    Name: "Henry Wilson",
    Email: "henry.wilson@example.com",
    Gender: "Male",
    Mobile: "9876543217",
    Designation: "Developer",
    Course: "B.Tech",
    Image: "henry.jpg",
  },
  {
    ID: "1009",
    Name: "Isla Martinez",
    Email: "isla.martinez@example.com",
    Gender: "Female",
    Mobile: "9876543218",
    Designation: "Analyst",
    Course: "MBA",
    Image: "isla.jpg",
  },
  {
    ID: "1010",
    Name: "Jack Anderson",
    Email: "jack.anderson@example.com",
    Gender: "Male",
    Mobile: "9876543219",
    Designation: "Team Lead",
    Course: "B.Tech",
    Image: "jack.jpg",
  },
  {
    ID: "1011",
    Name: "Karen Thomas",
    Email: "karen.thomas@example.com",
    Gender: "Female",
    Mobile: "9876543220",
    Designation: "HR",
    Course: "BBA",
    Image: "karen.jpg",
  },
  {
    ID: "1012",
    Name: "Leo Harris",
    Email: "leo.harris@example.com",
    Gender: "Male",
    Mobile: "9876543221",
    Designation: "Manager",
    Course: "M.Tech",
    Image: "leo.jpg",
  },
];
